
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap [denite] <Nop>
nmap <Space>d [denite]

nnoremap <silent> [denite]r :<C-u>Denite unite:file_mru<CR>
nnoremap <silent> [unite]ll :<C-u>Denite line -auto-preview<CR>
nnoremap <silent> [denite]d :<C-u>Denite unite:directory_mru<CR>
nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
nnoremap <silent> [unite]sf :<C-u>DeniteBufferDir file_rec -split=tab<CR>
nnoremap <silent> [denite]sg :<C-u>DeniteProjectDir file_rec -split=tab<CR>
nnoremap <silent> [denite]f :<C-u>DeniteBufferDir -buffer-name=files unite:file<CR>
nnoremap <silent> [denite]o :<C-u>Denite outline -auto-preview -no-empty<CR>
nnoremap <silent> [denite]c :<C-u>Denite change -auto-preview -no-empty<CR>
nnoremap <silent> [denite]J :<C-u>Denite jump -auto-preview -no-empty<CR>
nnoremap <silent> [denite]ta :<C-u>Denite tag -auto-preview -no-empty<CR>
nnoremap <silent> [denite]tk :<C-u>DeniteCursorWord tag -auto-preview -no-empty -immediately-1<CR>
nnoremap <silent> [denite]k :<C-u>DeniteCursorWord tag -immediately -no-empty<CR>
nnoremap <silent> [denite]n :<C-u>Denite -resume -select=+1 -immediately<CR>
nnoremap <silent> [denite]N :<C-u>Denite -resume -select=-1 -immediately<CR>
'''
hook_post_source = 'source ~/.vim/rc/plugins/denite.vim'

[[plugins]]
repo = 'tmn-o3/denite-autocmd'
hook_add = 'nnoremap <silent> [denite]a :<C-u>Denite autocmd<CR>'

