
- name: install with homebrew
  homebrew: name={{ item }}
  with_items:
    - lynx
    - tree
    - wget
    - nkf
  when: is_macos

- name: install dependencies with yum
  yum: name={{ item }} enablerepo=epel
  with_items:
    - lynx
    - tree
    - wget
    - nkf
  when: is_centos
  become: yes
