
version: '2'

volumes:
    dotfiles:
        driver: 'local'
    dein:
        driver: 'local'
    cache:
        driver: 'local'
services:
    neovim:
        build: .
        environment:
            - DISPLAY
        ports: 
            - 2489:2489
        volumes:
            - /c/Users:/c/Users
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /vagrant:/vagrant
            - dotfiles:/home/user/dotfiles
            - dein:/home/user/.vim/dein
            - cache:/home/user/.cache
        user: user
        working_dir: /home/user
