- hosts: 'local'
  roles:
    - { role: 'workspace', tags: 'workspace' }
    - { role: 'git', tags: 'git' }
    - { role: 'bash', tags: 'bash' }
    - { role: 'ruby', tags: 'ruby' }
    - { role: 'golang', tags: 'golang' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'tools', tags: 'tools' }
    - { role: 'python', tags: 'python' }
    - { role: 'php', tags: 'php' }
    - { role: 'node', tags: 'node' }
    - { role: 'docker', tags: 'docker' }
    - { role: 'neovim', tags: 'neovim' }
    - { role: 'ctags', tags: 'ctags' }
    - { role: 'pt', tags: 'pt' }
    - { role: 'timezone', tags: 'timezone' }
    - { role: 'tmux', tags: 'tmux' }
    - { role: 'xvfb', tags: 'xvfb' }
    - { role: 'gitconfig', tags: 'gitconfig' }
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
