- hosts: 'local'
  roles:
    - { role: 'unarchive', tags: 'unarchive' }
    - { role: 'bash', tags: 'bash' }
    - { role: 'zsh', tags: 'zsh' }
    - { role: 'workspace', tags: 'workspace' }
    - { role: 'ruby', tags: 'ruby' }
    - { role: 'golang', tags: 'golang' }
    - { role: 'mac', tags: 'mac' }
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'tools', tags: 'tools' }
    - { role: 'python', tags: 'python' }
    - { role: 'php', tags: 'php' }
    - { role: 'node', tags: 'node' }
    - { role: 'docker', tags: 'docker' }
    - { role: 'neovim', tags: 'neovim' }
    - { role: 'web_browser', tags: 'web_browser' }
    - { role: 'firefox', tags: 'firefox' }
    - { role: 'terminal', tags: 'terminal' }
    - { role: 'tmux', tags: 'tmux' }
    - { role: 'vim', tags: 'vim' }
    - { role: 'mysql', tags: 'mysql' }
    - { role: 'font', tags: 'font' }
    - { role: 'git', tags: 'git' }
    - { role: 'ctags', tags: 'ctags' }
    - { role: 'pt', tags: 'pt' }
    - { role: 'gitconfig', tags: 'gitconfig' }
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
