- hosts: 'local'
  roles:
    - { role: 'unarchive', tags: ['unarchive'] }
    - { role: 'bash', tags: ['bash'] }
    - { role: 'zsh', tags: ['zsh'] }
    - { role: 'workspace', tags: ['workspace'] }
    - { role: 'dotfiles', tags: ['dotfiles'] }
    - { role: 'neovim', tags: ['neovim'] }
    - { role: 'mac', tags: ['mac'] }
    - { role: 'tools', tags: ['tools'] }
    - { role: 'python', tags: ['python'] }
    - { role: 'node', tags: ['node'] }
    - { role: 'docker', tags: ['docker'] }
    - { role: 'font', tags: ['font'] }
    - { role: 'git', tags: ['git'] }
    - { role: 'ctags', tags: ['ctags'] }
    - { role: 'golang', tags: ['golang'] }
    - { role: 'aws', tags: ['aws'] }
    - { role: 'gh', tags: ['gh'] }
    - { role: 'deno', tags: ['deno'] }
    - { role: 'gitconfig', tags: ['gitconfig'] }
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
