- hosts: 'local'
  roles:
    - 'git'
    - 'bash'
    - 'workspace'
    - 'mac'
    - 'dotfiles'
    - 'tools'
    - 'python'
    - 'php'
    - 'node'
    - 'docker'
    - 'neovim'
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
